p8105_hw1_jpv2129
================
Jake Vettoretti
2025-09-18

## Problem 1

Loading the dataset

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
data("early_january_weather") #loads the dataset
```

Getting the number of rows/columns in the dataset and mean temp from the
dataset.

``` r
nrow(early_january_weather) #gets rows
```

    ## [1] 358

``` r
ncol(early_january_weather) #gets columns
```

    ## [1] 15

``` r
mean(with(early_january_weather, temp)) #calculating the mean temp
```

    ## [1] 39.58212

Dataset description: There are 15 variables in the dataset.

The names of the variables are: origin, year, month, day, hour, temp,
dewp, humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib,
and time_hour.

The important variables seem to be temp, dewp, humid, wind_dir,
wind_speed, wind_gust, precip, pressure, and visib as these are the
variables listed that mainly contribute to weather patterns.

There are 15 columns in the dataset and 358 rows (or observations).

The mean temp from the dataset is 39.58212 F.

Scatterplot:
